### ISSUE TITLE
request: webhook

### ISSUE THREAD

**Issue by theboy181** [cxd4/rsp#13]
Can you please add the webhook for Yappybot (discord)

This will allow the Discord community get update information from your project

Create webhook to https://www.yappybots.tk/

More information here.
https://github.com/YappyBots/YappyGithub

**Comment by cxd4** [comment]
What is Discord, and why should people care about it?

**Comment by theboy181** [comment]
this webhook lets discord users see any commits, PR's, issues.  I know that you might not see a reason for it so you can just say no and close the issue if you choose. Just thought I would ask if you would mind.

**Comment by cxd4** [comment]
That all depends on an answer to my question.

I don't understand webhooks.  If I understood Discord, I'd probably research into it, but if nobody wants to tell me why Discord matters then I'm indifferent to whether the issue remains open or closed.

**Comment by theboy181** [comment]
Discord is like Skype but it’s becoming a great place for people to hangout. There are now bots that can inform discord users of changes on github.

**Comment by cxd4** [comment]
An IRC hook has been added which addresses this issue.

**Comment by oddMLan** [comment]
>Discord

It's sorta like IRC with a twist (with servers, channels and all) but web-based and messages are persistant. So in practice, it is more similar to the MSN Messenger/Skype. Skype is dead in the water though, no people use it besides businesses. The Discord group we have it's pretty chill, a lot of familiar faces from the scene and some worthwhile discussion is going on most of the time.

**Comment by cxd4** [comment]
I don't really recall messages being persistent with Windows Live/MSN Messenger.

Unless you mean offline messaging--read a message that was sent to you while you were offline or disconnected.  IRC has that too if you use MemoServ.

**Comment by oddMLan** [comment]
You're right, MSN Messenger wasn't persistant (unless you did a manual backup), what I meant instead, a full message history gets preserved online, so you can see the message history accross any web browser or OS that supports the Discord client. That of course implies offline messaging.

**Comment by cxd4** [comment]
There was some sort of trial-ware cruft called IRC Cloud I think.

It sounds like the same effect as what you described.  You would connect to IRC using a web app in a browser and see a full history of the conversations transpired on the channels since you last connected.

I don't really go for that kind of thing though since having a stable Internet connection and just messaging groups of people that care enough to show up usually wins out for me.  The IRC Cloud effect is basically attained by proxying your connection through a bouncer service that stays online 24/7 to listen to chats overnight, if said effect is desired.

Also, fundamentally, the fact that Discord supports, as a protocol, preserved (offline) messaging history entails registration of some sort.  You have to be identified by more than just your local machine for it to work.  IRC is a protocol devoid of those concepts of registration or user accounts, so said effects are maintained anonymously.

**Comment by theboy181** [comment]
Not quite a no or a yes. Thanks anyway.
