### ISSUE TITLE
How to emulate DP clock counter 

### ISSUE THREAD

**Issue by olivieryuyu** [cxd4/rsp#14]
Hello

I have a N64 graphic command using DP clock counter (MFC0 V0, DP clock counter)

How to emulate this properly? We would need to fetch a clock counter to get a value but how can it work in HLE or simulate in HLE (for the graphic plugin?)

Thanks for advice!

**Comment by loganmc10** [comment]
The clock counter simply increments on each cycle of the RDP. The GFX plugin accesses it via the DPC_CLOCK pointer (https://github.com/loganmc10/GLideN64/blob/master/src/N64.h#L16)

The emulator core also has access to it, and the clock counter can be cleared by the RSP or the CPU. (via a write to the DPC_STATUS register).

As for how to emulate it, that will probably require some trial and error, I would just do something like: each time the game tries to read that register, add some random value to it before returning the answer.

One problem you might run into is that mupen64plus (and I think Project64) don't actually clear that value ever. The game is supposed to be able to write DPC_CLR_CLOCK_CTR to DPC_STATUS_REG, and that should reset DPC_CLOCK to 0, but the emulator doesn't implement that currently (it would be very easy to add though)

**Comment by olivieryuyu** [comment]
The rsp ucode read this register to get a random value i guess. Thanks!

**Comment by loganmc10** [comment]
Yes other games do a similar thing for the CPU clock counter. For instance, in the intro to Super Smash Bros, a random character is pulled from the box. The game does this by reading the CP0_COUNT_REG register (same kind of counter but it count CPU cycles, not RDP cycles).

If I was to emulate it in HLE, I would just return a random number, but I would make sure whatever random number I returned was higher than the last one, since it is supposed to be counting up.

**Comment by LegendOfDragoon** [comment]
Can you provide the snippet of code that uses this register? It could be helpful for figuring out what to do

**Comment by cxd4** [comment]
You're welcome @olivieryuyu. :P

@LegendOfDragoon , you say "the" snippet of code?  Is there something specific you're asking?

**Comment by LegendOfDragoon** [comment]
Some people say that the particle effects don't work right in LLE for Indiana Jones because the DPC clock register isn't being emulated. So I wanted to see how it's being used in the RSP microcode for Indiana Jones. The portion of microcode I dumped, doesn't have this part and I don't really know how to play the game lol.

**Comment by cxd4** [comment]
Ah, so that's what this is about.

My inference of the clock counter for the RDP is that it's simply incremental outside the RSP hardware.  As Logan explained, it increments on each "cycle" of the RDP, so in a cycle-accurate environment we probably wouldn't have to worry about adding a random value using `rand() % 100` or the like.

>The portion of microcode I dumped, doesn't have this part and I don't really know how to play the game lol.

I don't think the RSP has anything to do with this setting unless you either want to force the counter by overriding it to some special-purpose value you have in mind using MTC0 on the RSP or by resetting the counter to 0 (which could have been done by the CPU just as easily as by the RSP, if not even more easily).

So it's not something you're likely to encounter in any RSP microcode dumps.  Writing it, clearing it, updating it...stuff I've had message prompts in my RSP plugin for years yet haven't found a game doing that stuff.  Well, clearing it maybe.
