### ISSUE TITLE
Donkey Kong 64 EU with Project64 returns "unknown task type: 0x8BC43B5D" on launch

### ISSUE THREAD

**Issue by Searinox** [cxd4/rsp#25]
Tested with PJ64 official version 2.3 and recent nightly 2.4 builds from emuCR. A command prompt window with that error pops when starting the game. So far tested 5 other games and all ran without issues, except this one. Note that after the popup is closed, emulation begins normally.

**Comment by cxd4** [comment]
You are probably using the pre-built binary I had uploaded to EmuTalk.

This is generally a good thing except that due to a lack of feedback sent to me I never found the time to update the binary with all changes made since then.

See for reference:  https://github.com/cxd4/rsp/commit/11176630e12593a3e11cb5e90789a9b0df8aed7b
