### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by bladeoner** [cxd4/rsp#26]
When building on a Linux system (Linux Mint in my case) the build fails with the following errors as noted in an open issue at Mupen64Plus https://github.com/mupen64plus/mupen64plus-rsp-cxd4/issues/47. Any idea how to solve it? It started after https://github.com/cxd4/rsp/commit/cc4a5bb. I'm using Clang/LLVM to build. Thanks in Advance:

../..//vu/multiply.c:379:16: note: in expansion of macro ‘_mm_cmplt_epu16’
     overflow = _mm_cmplt_epu16(acc_lo, prod_lo); /* a + b < a + 0 ? ~0 : 0 */
                ^~~~~~~~~~~~~~~
../..//vu/multiply.c:379:14: error: incompatible types when assigning to type ‘v16’ from type ‘int’
     overflow = _mm_cmplt_epu16(acc_lo, prod_lo); /* a + b < a + 0 ? ~0 : 0 */
              ^
../..//vu/multiply.c:382:18: error: incompatible types when assigning to type ‘v16’ from type ‘int’
     overflow_new = _mm_cmplt_epu16(acc_md, prod_hi);
                  ^
../..//vu/multiply.c:386:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(v16 *)VACC_M = acc_md;
../..//vu/multiply.c:391:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(v16 *)VACC_H = acc_hi;
../..//vu/multiply.c: In function ‘macu_v_msp’:
../..//vu/multiply.c:440:15: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     acc_lo = *(v16 *)VACC_L;
../..//vu/multiply.c:441:15: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     acc_md = *(v16 *)VACC_M;
../..//vu/multiply.c:442:15: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     acc_hi = *(v16 *)VACC_H;
../..//vu/multiply.c:445:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(v16 *)VACC_L = acc_lo;
../..//vu/multiply.c:446:14: error: incompatible types when assigning to type ‘v16’ from type ‘int’
     overflow = _mm_cmplt_epu16(acc_lo, prod_lo); /* a + b < a + 0 ? ~0 : 0 */
              ^
../..//vu/multiply.c:449:18: error: incompatible types when assigning to type ‘v16’ from type ‘int’
     overflow_new = _mm_cmplt_epu16(acc_md, prod_hi);
                  ^
../..//vu/multiply.c:453:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(v16 *)VACC_M = acc_md;
../..//vu/multiply.c:458:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(v16 *)VACC_H = acc_hi;
../..//vu/multiply.c:463:14: error: incompatible types when assigning to type ‘v16’ from type ‘int’
     overflow = _mm_cmplt_epi16(acc_md, vs);
              ^
../..//vu/multiply.c: In function ‘madl_v_msp’:
../..//vu/multiply.c:502:15: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     acc_lo = *(v16 *)VACC_L;
../..//vu/multiply.c:503:15: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     acc_md = *(v16 *)VACC_M;
../..//vu/multiply.c:504:15: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     acc_hi = *(v16 *)VACC_H;
../..//vu/multiply.c:507:6: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     *(v16 *)VACC_L = acc_lo;
../..//vu/multiply.c:509:14: error: incompatible types when assigning to type ‘v16’ from type ‘int’
     overflow = _mm_cmplt_epu16(acc_lo, prod_hi); /* overflow:  (x + y < y) */
              ^
In file included from ../..//vu/select.h:19,
                 from ../..//vu/select.c:16:
../..//vu/select.c: In function ‘do_lt’:

**Comment by cxd4** [comment]
Sorry, I couldn't say why Mupen64Plus's fork is having errors with it since I had nothing to do with the generation of that fork.

You asked for some ideas of what might be wrong...one suggestion I would make is see this error:
```
../..//vu/multiply.c:379:16: note: in expansion of macro ‘_mm_cmplt_epu16’
overflow = _mm_cmplt_epu16(acc_lo, prod_lo); /* a + b < a + 0 ? ~0 : 0 /
../..//vu/multiply.c:379:14: error: incompatible types when assigning to type ‘v16’ from type ‘int’
overflow = _mm_cmplt_epu16(acc_lo, prod_lo); / a + b < a + 0 ? ~0 : 0 */
```

So an important question to ask is:  Why would your fork be seeing an intrinsic function as type `int`?  You indeed cannot assign a scalar type like `int` to a SIMD vector data type.  Nothing in my code even attempts this, regardless of which compiler you use.

Technically, though, _mm_cmplt_epu16 is not an intrinsic function.  It's a macro I wrote for a missing SSE2 instruction we don't get to have, which the Mupen64Plus fork correctly maintains my definition of.
```c
#define _mm_cmplt_epu16(dst, src)               \
    _mm_cmplt_epi16(                            \
        _mm_xor_si128(dst, _mm_setmin_epi16()), \
        _mm_xor_si128(src, _mm_setmin_epi16())  \
    )
```

All of these are well-defined, standard intrinsic functions in Intel's API.
* https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_cmplt_epi16
* https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_xor_si128
* https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm_slli_epi16

I do not see any difference between whether you choose to use GCC or Clang, but unless Clang incorrectly implements Intel's standard API for some particular vector instruction, then this should not be a compiler issue.  Conversely, it's not an issue with my code because redefining vector intrinsic functions to return type `int` would be illegitimate for me to even attempt if I'd wanted to.  It's clearly something wrong with the port, not this repository.

**Comment by bladeoner** [comment]
@cxd4 Thank you for you explanation.
