### ISSUE TITLE
Vector slice selections

### ISSUE THREAD

**Issue by bryanperris** [cxd4/rsp#27]
The RSP document (http://ultra64.ca/files/documentation/silicon-graphics/SGI_Nintendo_64_RSP_Programmers_Guide.pdf) 

describe how elements can be selected in most vector operations (eg: VADD, VMULF):

```
/* Normal */
if (inst.Element == 0) {
    j = i;
}

/* Quarter */
else if ((inst.Element & 0b1110) == 0b0010) {
    j = (inst.Element & 0b0001) + (i & 0b1110);
}

/* Half */
else if ((inst.Element & 0b1100) == 0b0100) {
    j = (inst.Element & 0b0011) + (i & 0b1100);
}

/* Whole */
else if ((inst.Element & 0b1000) == 0b1000) {
    j = (inst.Element & 0b0111);
}
```

In your non-SSE based vector routines, you only support the e = 0 case.  Was this intentional?

**Comment by cxd4** [comment]
I fail to envision where you must be looking since the scalar broadcasting support is side-by-side for the SSE and non-SSE code paths, which both implement the feature completely.

**Comment by bryanperris** [comment]
From multiply.c and N is equal 8.

word_64 product[N]; /* (-32768 * -32768)<<1 + 32768 confuses 32-bit type. */

register unsigned int i;

for (i = 0; i < N; i++)

product[i].W = vs[i] * vt[i];

for (i = 0; i < N; i++)

product[i].W <<= 1; /* special fractional shift value */

for (i = 0; i < N; i++)

product[i].W += 32768; /* special fractional round value */

for (i = 0; i < N; i++)

VACC_L[i] = (product[i].UW & 0x00000000FFFF) >> 0;

for (i = 0; i < N; i++)

VACC_M[i] = (product[i].UW & 0x0000FFFF0000) >> 16;

for (i = 0; i < N; i++)

VACC_H[i] = -(product[i].SW < 0); /* product>>32 & 0xFFFF */

SIGNED_CLAMP_AM(V_result);

**Comment by cxd4** [comment]
Yes, this code in your excerpt is designed to be identical to the SSE code path in output.  When SSE is not available, the code you pasted is used to achieve the same behavior.  However, none of this would seem to have anything to do with why you suspect that scalar broadcasting is being handled in the vector unit by exactly one code path yet not the other.

**Comment by cxd4** [comment]
Perhaps this might help you.  Lines 1874 down through 1938.
https://github.com/cxd4/rsp/blob/3e3034988bd549f00795d9ba0a561bf870bb319f/su.c#L1874

**Comment by bryanperris** [comment]
So when a scalar whole is selected for example then it's a scalar broadcasting operation?

I just looked how iterators I and j are used in the vector source and target slice selections.

**Comment by cxd4** [comment]
As you can see from the jump table, if the COP2 sub-operation specifier is 0o020 (0b10000 or 0b10001), the vector operation is run on two entirely vector registers.  If the sub-operation specifier is 0o022 or 0o023, half of the second vector is interleaved across the vector itself to form a quarter-scalar vector.  If it is 0o024, 025, 026 or 027, a quarter of the vector is broadcasted intermittently across the identity vector to form a half-scalar vector.  If it is between 030 to 037, a single element's scalar value is broadcasted across the whole vector for a wholly scalar vector.

This is true regardless of whether using SSE or not.  But I would not be implementing this within each and every individual instruction, such as VMULF, because that would be polluting the vector unit module with repeated phase code belonging to the entire instruction class before entering vector mode anyway.

**Comment by bryanperris** [comment]
Thank you, this is very helpful.
