### ISSUE TITLE
Endianess

### ISSUE THREAD

**Issue by bryanperris** [cxd4/rsp#31]
I managed to hook up the RSP plugin into cor64 using CppSharp to build me the C# wrapper, everything works except the plugin is directly reading IMEM as little-endian and resulting in broken execution / infinite loop.  I provide all pointers via the RSP_INFO struct as expected by these pointers are pointing to data stored as big-endian.  

The next thing for me is to add some kind of ifdef EMUHOST_BE that will allow big-end access to any data exported by the RSP_INFO inteface.

**Comment by cxd4** [comment]
It depends on why you are passing data to the RSP plugin that was stored in big-endian.  Are you actually running and developing in an environment with a natively big-endian CPU architecture, or are you just accurately emulating the server-side N64 byte order on the client machine on which your emulator is running?

If it is the former, then it's entirely possible that my endianness auto-detection preprocessor macros are not complete enough to include your environment, so you might need to override it to test.

https://github.com/cxd4/rsp/blob/c3dd4c5a9c04965fc24d1d4cb0ab245f0b2f7e52/my_types.h#L434-L444

If it is the latter, you might only need to change the preprocessor setting within the RSP plugin to emulate the real N64 byte order, rather than using client-side machine's endianness (and also--next link--fix the byte-swapper macros to have an XOR mask of 0 so that no byte-swapping is done).

* https://github.com/cxd4/rsp/blob/04c2aba6a5f0efdcaa036703da06a091dd828cf7/su.h#L40-L50
* https://github.com/cxd4/rsp/blob/c3dd4c5a9c04965fc24d1d4cb0ab245f0b2f7e52/my_types.h#L446-L454

**Comment by bryanperris** [comment]
My development computer is Intel based.  The RAM I establish for the emulator including MMIO is big-endian.  The interpreters have to swap data to little-endian in order to process the data.

**Comment by cxd4** [comment]
Then the second half of my conditional response is what would apply.  You would then zero out the swap mask preprocessor operands.

**Comment by bryanperris** [comment]
Is that going to work fine for the BES and HES swap macros involved for vector load/stores?

**Comment by cxd4** [comment]
https://github.com/cxd4/rsp/blob/ee3cb4a9f6233a170db09729374c992ae8e30141/su.h#L234
https://github.com/cxd4/rsp/blob/ee3cb4a9f6233a170db09729374c992ae8e30141/su.h#L243-L244
https://github.com/cxd4/rsp/blob/ee3cb4a9f6233a170db09729374c992ae8e30141/su.h#L252

MES is like BES but just does the little-endian byte-swap over 16- rather than 32-bit boundaries.  So big-endian 0xAABBCCDD becomes 0xBBAADDCC rather than 0xDDCCBBAA.

Either way, they all reference the bit mask `ENDIAN_M`, so I guess you could just 0 that macro out for short.

**Comment by cxd4** [comment]
Actually, if I'm gathering your situation right, you're still compiling, running, and testing on an Intel/little-endian CPU?  But just forcing big-endian within the emulators?  Then you'll want the four VR_* macros above to stay little-endian, because your native machine is still writing to vector registers as an array of 8 16-bit ints.  Plugin is not going to constantly byte-swap back-and-forth every time a 16-bit integer gets operated on, so there's just no way to make those macros big-endian without blowing everything up and ruining the efficiency of things.

So those four will stay, with references to MES removed.
```c
#define VR_B(vt, element)       *((unsigned char *)&(VR[vt][0]) + ((element) ^ 1))
#define VR_A(vt, e)             *((unsigned char *)&amp;(VR[vt][0]) + e + 1)
#define VR_U(vt, e)             *((unsigned char *)&(VR[vt][0]) + e - 1)
#define VR_S(vt, element)       *(pi16)((unsigned char *)&(VR[vt][0]) + element) // no change
```

**Comment by bryanperris** [comment]
Yes to both questions.  I know there is a performance issue involved like you mentioned but this is needed just for comparing RSP cores to find out my RSP issue.  Eventually I will implement a way to allow the VM to run as little-endian or big-endian, just right now I want to process the data in its native format.  My C# core is doing byteswapping on load/stores and MMIO access, but since I put the swapping logic in common spots, you do not need to change a million lines of code to take out the swapping.  Optimization will come last as soon I can get a ROM to fully run that involves the CPU, RSP and RDP working together, for example getting the mupen64 test rom to fully run.

**Comment by cxd4** [comment]
So you were all set with the instructions I gave or was there something else having the ticket open?

**Comment by bryanperris** [comment]
I should be all set thanks.  Instructions are being executed now, just have to keep digging deeper to figure out the next issue that is preventing the RSP from passing any simple tests.

**Comment by bryanperris** [comment]
Here is some DMEM logic I found that breaks things in my emulator (BES is also 'disabled'):

    DMEM[BES(addr + 0) & 0x00000FFFul] = SR_B(rt, 0);
    DMEM[BES(addr + 1) & 0x00000FFFul] = SR_B(rt, 1);
    DMEM[BES(addr + 2) & 0x00000FFFul] = SR_B(rt, 2);
    DMEM[BES(addr + 3) & 0x00000FFFul] = SR_B(rt, 3);

32-bit value pointed by rt is swapped from little-endian to big-endian, then back to little-endian.  Turning off BES doesn't fix the issue because the native memory storage is in little-endian order.  So why bother using BES for little-endian native machines?

For my situation, I do need the byteswapping on just the right side.

**Comment by cxd4** [comment]
>So why bother using BES for little-endian native machines?

Because the server-side is not also a little-endian machine.

>32-bit value pointed by rt is swapped from little-endian to big-endian, then back to little-endian.

32-bit scalar is not swapped at all; see macro comments.
https://github.com/cxd4/rsp/blob/ee3cb4a9f6233a170db09729374c992ae8e30141/su.h#L217-L221

`SR_B` has the same purpose as `VR_B` and friends except that it's not for vector registers, so I forgot to list it here.

Like before when I gave you the hard-coded replacement of the BES macro for `VR_B`, you would need to do the same for `SR_B` for the same reasons.  (Don't forget you disabled BES globally at the very beginning when setting the endian swap masks to 0.)  Since scalars are twice as wide as vector slices, the XOR mask to swap by is 3 rather than 1.  So it should be `((i) ^ 3)`.

>I should be all set thanks. Instructions are being executed now, just have to keep digging deeper to figure out the next issue that is preventing the RSP from passing any simple tests.

OK sounds good; I have never had access to any big-endian plugin spec so I cannot test-develop it myself.

**Comment by bryanperris** [comment]
I got SU and VU tests working :)
