### ISSUE TITLE
Behavior of message() on non-windows targets

### ISSUE THREAD

**Issue by bryanperris** [cxd4/rsp#32]
The message function shouldn't wait on user input since this is just a library, also it only needs to execute: `printf("%s\n", body);`

**Comment by cxd4** [comment]
I'm not really sure why anyone would invoke the extra work of `printf` on something that's not needing to do any character conversion; if you already have the exact string literal that you know you want sent verbatim to the output stream, you have a myriad of simpler, more efficient standard library routines designed to just put out that.

The `MessageBox` function on Microsoft Windows waits on user input all the time on Win32-based plugins in the form of requiring the user to acknowledge the error with a button click before emulation can continue, so I'm not sure I understand the precise merit of this issue -- but I do agree on the Linux subsystem it is hard to find the terminal session waiting for a keystroke to resume on some distributions.  Neither fatal errors nor trivial errors in the RSP are particularly likely, so I don't see the harm in changing the console output to just passively list everything by on release builds.

**Comment by bryanperris** [comment]
Interesting point about the printf function.

I understand the need to popup the dialog as since PJ64 works as such, but I have seen message get invoked for "config not found" and if I execute DoRspCycles while the RSP is technically halted.

**Comment by cxd4** [comment]
Oh yeah, stuff like that's garbage.  Well, compared to the other error messages that are more indicative of fatal errors (or even worse, non-fatal errors that allow emulation to continue with deafeningly screechy RSP audio).  I used to have the message printing done in another way that passed a priority level indicating the likelihood that it should even disturb the user on-screen at all, but that was a long, long time ago.

**Comment by cxd4** [comment]
Thinking back to the printf() issue, I remember almost a decade ago the version of gcc back then when optimizing with -O2 or -O3 optimization levels compiled a simple `printf("Hello, world!\n")` as just a call to `fputs` or `puts`.  (I would prefer the latter if we want the line feed ending the string implicitly.)  You could try this with today's version of gcc with something like `gcc -o output.asm main.c` and look at the assembly output if you wanted.  It's not a substantial performance concern, but I think printf() is just popular from all those C beginner books because it avoids teaching a bunch of halfway duplicate, lower-level string output functions that are actually a lot simpler but just less flexible.

**Comment by bryanperris** [comment]
It is good thing to know for embedded low powered devices (eg: ESP32)

**Comment by bryanperris** [comment]
Another thing I did to it was add a prefix "RSP PLUGIN: ", that way it is obvious what messages came from the RSP plugin itself.

**Comment by cxd4** [comment]
I forgot if RetroArch does something similar for their style of modularization as well.  Had the original plugin spec for N64 emulators had a standard error-reporting routine (i.e., a pointer passed from the core to each plugin to the function for displaying errors), this would have been very easy to centralize.  Though, even in plain mupen64 console output, I can definitely tell its own CPU or other plugins' error messages apart from RSP op-code errors.
