### ISSUE TITLE
32 bit builds made with MSYS2 require dlls to be present in the Project 64 folder/have make_w32.cmd default to MSYS2 as the default compiler

### ISSUE THREAD

**Issue by Yersho** [cxd4/rsp#33]
Compiled 32 bit builds made with MSYS2 require 2 dlls to be present in the main Project 64 folder or else the program cannot detect or use the compiled rsp plugin. Both dlls can be found in C:\msys64\mingw32\bin, assuming the default install location of MSYS2 is used. The dlls are:

- libgcc_s_dw2-1.dll
- libwinpthread-1.dll

This behavior is not true for the 64 bit version built with MSYS2. Using 64 bit builds made with MSYS2 with Project 64's 64 bit version does not require the dlls and can be used as is by simply putting the rsp plugin in Project 64's RSP plugin folder. Is this intended behavior or is there something wrong here? I built the 32 bit version by replacing "set MinGW=C:\MinGW" with "set MinGW=C:\msys64\mingw32" in make_w32.cmd like the comment in said file states to. I have made no other modifications to source or the build scripts.

Rather than make two issues I'll just quickly add this here since it's related to the subject. Can make_w32.cmd default to MSYS2? I don't see a good reason to be using older software that isn't really updated when MSYS2 achieves the same result, is updated regularly, and is also the default for make_w64.cmd.

**Comment by cxd4** [comment]
Did not actually put any comments in `make_w32.cmd` saying to switch from original MinGW to MSYS...that was just a commented-out thing I left behind so that people could toggle it for themselves if they wanted to for some reason.  I only ever tested the Windows port of the plugin by using the official MinGW.

Are you reporting that those extra DLL files are being required when the plugin is linked by MinGW, or are you reporting that they're a requirement when changing the 32-bit version to `set MinGW=C:\msys64\mingw32`?

**Comment by Yersho** [comment]
Sorry if my wording was weird, I never meant to imply you wanted to switch from MinGW to MSYS. I was just referring to the commented out setting. Yes when changing the line to `set MinGW=C:\msys64\mingw32` in make `make_w32.cmd` the extra dll files become required.

I was requesting you at least consider switching the 32 bit build to use MSYS2 by default since MSYS2 is kept much more up to date compared to MinGW.

**Comment by cxd4** [comment]
Nah, no worries.  It was more the way I worded it in the CMD script ("the only line you *should* need to change" (but shouldn't necessarily (have to))).

I suppose MSYS fork can be defaulting to a different static/dynamic linker flag for `libgcc_s` for 32-bit targets vs. when targeting 64-bit.  Normally GCC has a flag you can toggle to link the DLL statically for dynamically.  It used to not matter because until recent versions of MinGW (which caused someone else to have to submit a pull request to fix my script a year back) I was able to just call `ld` directly at the very end of the CMD file, not `gcc`.

So you could try changing
```sh
gcc --shared -e _DllMain@12 -o "%obj%\rspdebug.dll" -L %lib% %OBJ_LIST% -lmsvcrt
```
to
```sh
ld --shared -e _DllMain@12 -o "%obj%\rspdebug.dll" -L %lib% %OBJ_LIST% -lmsvcrt
```
...which used to work back when I had Microsoft Windows installed myself to test development on but some years later I guess either they (or MSYS fork of them) broke that.  If that works then you would avoid implicit linkage of irrelevant libraries like winpthread that I never intended as dependencies of my RSP code.  If that doesn't work then, well, such is life on an OS I gave up testing years ago I guess.  I do not have time to figure much Windows stuff out.

More to the point of your post, is there any benefit to switching from MinGW to MSYS for the 32-bit build?

**Comment by Yersho** [comment]
Changing
```
gcc --shared -e _DllMain@12 -o "%obj%\rspdebug.dll" -L %lib% %OBJ_LIST% -lmsvcrt
```
to
```
ld --shared -e _DllMain@12 -o "%obj%\rspdebug.dll" -L %lib% %OBJ_LIST% -lmsvcrt
```
did not work as the plugin failed to compile. However I believe using the `-static` flag will work. I compiled the plugin with the flag and tested it out and it seemed to no longer require the dlls to be present in order for Project 64 to use the plugin. I myself have very little experience with this stuff though so feel free to correct me here.
Source I used to find the flag:
https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html
I don't know why the 64 bit build script does not require any flags to be statically linked but maybe it should also be added to `make_w64.cmd` as future proofing?

As for switching the default compiler to MSYS2 for `make_w32.cmd` I believe the main benefit would be convenience. Most projects I've come across use MSYS2 for both it's ability to build 64 bit Windows programs and it's ability to compile 32 bit programs as well. There really isn't a need to have two programs to compile 32 bit programs when you have one program to compile both 32 bit and 64 bit programs. MSYS2 also has more packages, afaik, and is more up to date in general. It seems MinGW is only at GCC version 9.2 while MSYS2 is at 10.3.
https://osdn.net/projects/mingw/releases/
https://packages.msys2.org/base/mingw-w64-gcc

**Comment by cxd4** [comment]
Changing the `gcc` to `ld` would not have actually any effect on compilation.  By the time it gets to that line at the bottom, compilation to the x86 asm files has already long completed.  The problem is that MSYS began requiring additional dependencies to be auto-linked into simple DLLs that MinGW did not force dependencies with (such as I remember `winpthread` being one of them indeed).  They probably don't use pthreads for 64-bit builds because 64-bit Microsoft Windows already implies multi-threading support.  (This plugin never does anything with multi-threading anyway or let alone takes advantage of that....)

I am sure that `-static` would work as you say to remove the external DLL dependencies; however all that does is statically link the portions of the needed DLL files into the file size of `rsp.dll` and just make the plugin larger.  One good reason I used to call `ld` directly rather than `gcc` was to eliminate unintended dependency generation altogether (rather than statically link it / make it invisible as a growth to the file size of my plugin) and that if it failed to link the plugin without those dependencies, it would not create the plugin with the problems hidden, but throw a link-time error so that I could be aware of the issue and find a different solution to not generate them in the first place.  So I will never accept defaulting `-static` as a solution.

>As for switching the default compiler to MSYS2 for make_w32.cmd I believe the main benefit would be convenience. Most projects I've come across use MSYS2 for both it's ability to build 64 bit Windows programs and it's ability to compile 32 bit programs as well. There really isn't a need to have two programs to compile 32 bit programs when you have one program to compile both 32 bit and 64 bit programs. MSYS2 also has more packages, afaik, and is more up to date in general. It seems MinGW is only at GCC version 9.2 while MSYS2 is at 10.

OK.  So to me it sounds like most of the reason is to have newest versions of GCC for more liklihood of up-to-date function optimizations (by being a little bit closer to the version numbers of GCC available natively on the GNU platform).

Some internal drama happened that caused MinGW 64-bit to split off and recede over to MSYS2 and I can't remember much about that.  I did not like how they did it.  As far as I'm concerned MinGW is still the official port of GCC to Windows and MSYS2 should only be required when building the 64-bit version of the plugin because that responsibility was taken away from the upstream MinGW project through some sort of political egocentricity that I can't remember well at all now.  I know you are mostly debating on the side of convenience and not political technicalities, but at the same time I have to consider what about 32-bit builds is more convenient than 64-bit builds.  Nothing about the 32-bit plugin should ever be faster than the 64-bit build, so if the reason for using the newer GCC ports/MSYS2 is convenience, I am not even sure why worry what the 32-bit build script does.  Not saying some reasons couldn't exist, just saying how I see it until I find time into looking at a compromise for this.

**Comment by Yersho** [comment]
- Why use the 32 bit version:
Project 64 32 bit only supports 32 bit plugins. Project 64 64 bit version only supports 64 bit plugins. Currently Project 64 64 bit version only supports the interpreter core and has minor GUI issues when applying settings. GUI changes to an older theme that I'm not 100% positive on exactly what, probably aero. The GUI issues don't actually effect the usage of the program however being stuck with interpreter can be a performance decrease on older hardware. I am also not 100% positive if there are any other issues with the 64 bit version of Project 64 however there shouldn't be.

- Regarding the `-static` flag:
I never wanted to force you to do anything. However if nothing else can be done can a comment to the build script for the 32 bit version be added to let users of MSYS2 know to add it to the end? This leaves your original script untouched and lets users decide to use it if they so choose. As a follow up question, why does the 64 bit build made with MSYS2 not have the dll dependency problem, is it automatically statically linking them or is it doing something else? Because 32 bit builds also need a dll for what I believe is the gcc compiler.

- Switching to MSYS2 as the default for `make_w32.cmd`:
Again, don't want to force you to do anything. I am perfectly fine with it being just an option and not a default. I just added that to this issue just to not make two issue reports for similar topics.

- Using `ld` instead of `gcc`:
For both `make_w32.cmd` and `make_w64.cmd` I can provide said error when compiling with MSYS2. Will only include the relevant part of the output as everything else works as expected.

`make_w32.cmd`
```
Linking assembled object files...
ld: cannot find -lmsvcrt
```
`make_w64.cmd`
```
Linking assembled object files...
ld: C:\msys64\home\yershi\test\rsp\obj\module.o:module.c:(.text+0x27): undefined reference to `__mingw_vsprintf'
```
I think this goes over everything in your reply. Sorry if I missed anything.

**Comment by cxd4** [comment]
I have an idea.  Perhaps unconditionally compile with official MinGW if and only if the user chose to install it (normal installation always goes to `C:\MinGW\`)?  All I have to do is check via Windows shell conditional statements if that directory exists or not.  If it doesn't, it's safe to assume the user either doesn't know about MinGW or just chose not to install it--in which case, MSYS2 will be the fallback search path to try.

So if I implement this, all you have to do is choose not to install MinGW, and MSYS2 will get used?

>```ld: C:\msys64\home\yershi\test\rsp\obj\module.o:module.c:(.text+0x27): undefined reference to `__mingw_vsprintf'```

Yes, correct; that is the reason why I found I was forced to change the line from `ld` to `gcc`.  My point is that it is not a compilation issue.  For it to get that far up to that error, all compilation has succeeded, but the linkage of the binary is what has failed because `gcc` calls the linker `ld` implicitly while passing all the required library search paths, while making a direct call to `ld` as I was doing earlier will fail to upload standard search paths unless I explicitly list them all (which I was too lazy to figure out which one was missing, so I changed to `gcc` as a hot-fix).

Matter of fact, that reminds me I forgot it was actually you who brought that issue to my attention some time ago.
https://github.com/cxd4/rsp/issues/28 (Just for reference.)

I knew I could fix it without changing the `ld` to `gcc` but the problem is I have to figure out which CRT/library search path specified by the `-L` command-line flag is missing in the call to `ld`, that simply changing to `gcc` implicitly adds and figures out for you anyway.  I had to settle for the quick fix because I just do not have a Microsoft operating system I can test on anymore.

Having said that, the odds of changing it back to directly call LD.EXE while fixing your old linker failure the hard way (correct way) removing the extra DLL dependencies being generated for pthreads and libgcc are not 100% guaranteed, so it's probably not worth the time and effort to revisit that issue.  I'm merely saying all of this to reflect on decisions I forgot that I made.

**Comment by cxd4** [comment]
Some follow-up stuff that's not quite to the chase here --

>As a follow up question, why does the 64 bit build made with MSYS2 not have the dll dependency problem, is it automatically statically linking them or is it doing something else? Because 32 bit builds also need a dll for what I believe is the gcc compiler.

64-bit ISA guarantees multi-threading support, so libpthreads must not be a meaningful dependency on 64-bit builds.  That's the only explanation I can think of but don't know much about the process-threading arena; that is probably why I didn't do a good job of explaining that explicitly enough in my earlier follow-up so you missed that.  For some reason, MinGW does not add dependencies for 32-bit software being able to multi-thread, but MSYS2 links them in "just in case".  I cannot say why; all I can tell you is that the 64-bit kernel unconditionally supports that feature all on its own, in case that is what pthreads on Win32 is supposed to be about.

The second half of your question seems to be talking about the libgcc_s DLL.  That is a dependency I removed years ago by using the `-e DllMain` flag to direct the entry point to the DLL to a low-level offset (since Project64/N64 emulators are not really looking for a DllMain to call anyway).  This removes a lot of CRT startup code that never gets executed which depended on extra C run-time code from libgcc_s.  However, because MSYS2 is defaulting to multi-threaded coverage with pthreads library, it re-adds that dependency I took out by adding different code I never even conceived of having to remove.  So, that's an entirely separate problem that was born after I stopped having Windows partitions to test on anyway.  Don't know if that fills in any holes for you.

>The GUI issues don't actually effect the usage of the program however being stuck with interpreter can be a performance decrease on older hardware.

I think last time I checked they were spreading some myth around Project64 comments that the 64-bit build can't be endorsed due to interpreter-only.  I'm not really sure why people say that or what that has to do with anything.  VR4300/CPU dynamic re-compiler vs. interpreter core is highly non-sequitur in today's LLE environments.  That maybe was an issue on 0.5-GHz CPUs that ran N64 emulators that just HLE'd the entire console.  Nowadays, the RDP is required to be built in 64-bit to have better performance since there is no reason to have an RDP recompiler anyway.  So yes, probably Project64 does not support a recompiler for 64-bit yet, but that's probably because there is no benefit to having a recompiler...what they need to do if they want speed is optimize the RCP.  The RSP should have a 64-bit dynarec probably, yes, but the CPU is trivial.

**Comment by Yersho** [comment]
Project 64 64 bit version has a buggy GUI and no re-compiler support. Now whether or not interpreter is a major performance hit is irrelevant as currently no work is being done on this and won't until Project 64 has accuracy improvements. It won't be until Project 64 version 5.0 that the 64 bit build will have either of these issues fixed.
https://www.pj64-emu.com/support-project64.html
Because of this only 32 bit builds are uploaded by the build bot on Project 64's website. So the most accessible builds of Project 64 will be 32 bit and as such, require 32 bit plugins. You can build 64 bit builds of Project 64 yourself or get them from AppVeyor, but most people will be on the 32 bit build due to these reasons.

Having MinGW be the default and MSYS be the automatic fallback is a good idea. Saves time by having people not need to edit the script in a text editor. Also, when I compiled the 32 bit builds with the original MinGW after you pushed the pull request that closed the original issue I made, I never needed any dlls or external dependencies. I don't remember if using `ld` post pull request would cause linkage to fail as I never tested it. I assume it would still fail though.

I also found while testing using `ld` with `make_w32.cmd` that the `lib` and `inc` variables would need to be changed if using the MSYS2 version of MinGW 32 to:
```
lib=%MinGW%\i686-w64-mingw32\lib
inc=%lib%\..\include
```
This fixes the following error when using MSYS2 with `make_w32.cmd`
```
Linking assembled object files...
ld: cannot find -lmsvcrt
```
and instead makes the error:
```
Linking assembled object files...
ld: C:\msys64\home\yershi\test\rsp\obj\module.o:module.c:(.text+0x1d): undefined reference to `__mingw_vsprintf'
```
Which at least is the same as the `make_w64.cmd` error.

If you were to make `make_w32.cmd` choose to use MSYS2 only if MinGW is missing then this makes most of the comments regarding MSYS2's MinGW 32 in `make_w64.cmd` redundant as `make_w32.cmd` would now handle this. If you were to use `make_w64.cmd` and use MSYS2's MinGW 32 it would still technically be "wrong" as `make_w64.cmd` uses `DllMain` instead of `_DllMain@12` anyways.

So if you do decide to have `make_w32.cmd` fallback to MSYS2 if it does not detect MinGW installed, I propose the following changes when it does switch to MSYS2:

- Change `lib=%MinGW%\lib` to `lib=%MinGW%\i686-w64-mingw32\lib`.
- Change `inc=%MinGW%\include` to `inc=%lib%\..\include`.
- Add `-static` build flag. I know this isn't something you would want to do however considering this would only be used for when falling back to MSYS2 and would not affect the original build script when using the original MinGW I feel this an acceptable compromise until a proper solution is found regarding using MSYS2.

If the proposed changes are made to `make_w32.cmd` I would also propose the following changes to `make_w64.cmd`. Basically this removes the unnecessary comments regarding MSYS2 MinGW 32:

- Remove:
```
REM The following two variables are irrelevant, unless you set a 32-bit target.
set mingw32=%mingw64%\..\mingw32
set lib=%mingw32%\i686-w64-mingw32\lib
```

If you do decide to accept these changes I would also suggest either leaving this issue open or making a new one regarding the errors `ld` generates so that you don't forget the unwanted dependencies are being generated and can resolve them whenever you can.

**Comment by cxd4** [comment]
>You can build 64 bit builds of Project 64 yourself or get them from AppVeyor, but most people will be on the 32 bit build due to these reasons.

Should not have anything to do with the fact that using 64-bit is relevant for the importance of optimizing the RCP, not having a CPU dynarec.  Moreover last time I used 64-bit version of Project64 was years ago and it was in WINE on GNU and there were no problems obtaining it or running it.

>If you were to make make_w32.cmd choose to use MSYS2 only if MinGW is missing then this makes most of the comments regarding MSYS2's MinGW 32 in make_w64.cmd redundant as make_w32.cmd would now handle this.

There are no comments regarding MSYS2's MinGW 32-bit in `make_w64.cmd` so not sure what you mean.

There are a couple demonstrative/legacy variables that illustrate comparing the switch to 32-bit MinGW paths in `make_w64.cmd` if that is what you mean.  Not so much comments, but making the change you request to fall back on MSYS2 32-bit only if MinGW install cannot be found does not make either of them any more or less redundant before or after that change.

>If you were to use make_w64.cmd and use MSYS2's MinGW 32 it would still technically be "wrong" as make_w64.cmd uses DllMain instead of _DllMain@12 anyways.

It uses whether the entry-point-labeling produces for how to refer to DllMain, not what you or I tell it to use.

>So if you do decide to have make_w32.cmd fallback to MSYS2 if it does not detect MinGW installed, I propose the following changes when it does switch to MSYS2:

None of these are changes that are relevant to the primary change you are asking that I make.  The script was always designed to be interchangeable to target either the MinGW directory or the MSYS2 directory for choice of how to do the build, so your suggestions to change the parameters MSYS2 build do not require checking if MinGW is not installed first.

So there is no reason to make additional suggestions contingent upon whether I make an unrelated change.  It sounds as if you are trying to imply that making the Windows shell scripts auto-detect (rather than expect manual reconfig by the user) whether to choose MSYS2 over MinGW-32 somehow changes whether the parameters outlined for building by either one are important to consider.  It does not.

>I know this isn't something you would want to do however considering this would only be used for when falling back to MSYS2 and would not affect the original build script when using the original MinGW I feel this an acceptable compromise until a proper solution is found regarding using MSYS2.

The acceptable solutions are for you to a) not delete the DLL files needed by the MSYS2 build but rather keep them so the plugin requiring them will work, or b) not use MSYS2 if you prefer not having two more dependencies, or c) use your access to Microsoft Windows (which I do not have) to research how to get MSYS2 to not link in the pthreads dependency, or d) contact MSYS2 to fix the problem with their fork of your favorite compiler, or e) consider using the native GCC compiler by not using Windows or building and running the plugin in a non-Windows emulator on a faster operating system (for which these dependencies do not exist), or f) throw the `-static` build flag in yourself if you personally find the external DLL files that inconvenient, because I am never forcing everyone to use f) as their solution just because you are willing to accept the spike in file size to the plugin from statically linking does not mean everyone else is.  So do whatever you want in the script as far as the dependency issue on Windows but I am not imposing your preference on everyone else.  The external DLL files are fine as-is for those who would rather use MSYS2's extra dependencies.

>If you do decide to accept these changes I would also suggest either leaving this issue open or making a new one regarding the errors ld generates so that you don't forget the unwanted dependencies are being generated and can resolve them whenever you can.

I am sure anyone preferring to use MSYS2 over MinGW and seeing the two required DLL files (from not passing `-static` if they don't personally want to do so as you do) would not have any problems remembering to investigate it so I doubt that they would need this issue to stay open for them to not forget.  Remember I don't have Windows nor do I have any way of using Windows like you seem to expect me to just to test your favorite compiler so this is not my job to investigate MSYS2; it's yours.  This door was not opened by me.

On a related note, I've run out of time to try to research how Windows shell script syntax works for checking if a directory exists on an operating system I cannot test since I burned up that time by using it to reply to your extra philosophical additions in this ticket (none of which were pertinent to the organized issue of having it auto-detect which compiler to switch to or check if a file path does not exist for such), so I am afraid we're out of time and if you want that changed you'll need to test it on your Windows and submit the pull request for me.  Thanks.
