### ISSUE TITLE
Strange color with Nintendo Logo in Zelda: Ocarina of Time

### ISSUE THREAD

**Issue by orbea** [cxd4/rsp#7]
OS: `Slackware64-current`
`mupen64plus-2016.10.09_507893d-x86_64-1_git`

When using rsp-cxd4 with mupen64plus and the game Zelda: Ocarina of Time the Nintendo logo will have a strange color. This does not occur with rsp-hle and the video plugin does not make a difference. Is there a reason it looks like this?

Apitrace - http://ks392457.kimsufi.com/orbea/stuff/trace/mupen64plus/cxd4_nintendo_logo.trace.xz

**rsp-cxd4**
![cxd4](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/Zelda%20OoT%2064-161012-125634.png)
**rsp-hle**
![hle](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/mupen64plus/Zelda%20OoT%2064-161012-125621.png)

**Comment by orbea** [comment]
rsp-z64 does it too. I suspect this is either an issue directly with rsp-cxd4 or perhaps an issue with the mupen64plus-core which LLE rsps expose?

**Comment by cxd4** [comment]
I find no such issue on my 64-bit port of Mupen64, but I cannot comment on Mupen64 "Plus" given that I don't keep track of what goes on in their fork.

Raw CPU frame buffer:
![http://i.imgur.com/kRFnlLT.png]

Post-processed for DAC:
![http://i.imgur.com/c6KXpHt.jpg]

Does Mupen64Plus let you test an interpreter CPU core instead of dynamic re-compilers?  Maybe you should check if this graphical issue happens with the stable core.  If so, then I propose a regression in their fork of this RSP emulator.

I haven't yet upgraded to Slackware 14.2 or current from 14.1, although I doubt that's related.

>This does not occur with rsp-hle and the video plugin does not make a difference.

HLE RSP basically just means that the RSP is emulated by the video plugin, not the RSP plugin, so the fix can't come from within `rsp-hle`.  The fact that you don't see this issue when using the video plugin (any HLE video plugin, regardless of what you choose) to emulate the RSP instead of the RSP plugin emulating the RSP suggests further that this may be exposing an issue in the modified Mupen64 core as you suggested.

**Comment by orbea** [comment]
To be honest I have noticed for a while with angrylion in mupen64plus-libretro, but it was not till GLupeN64 added the cxd4 rsp that I realized it was connected to it. After this I confirmed it happens with upstream mupen64plus too for the gfx plugins that are able of using the cxd4 rsp.

Furthermore looking at your images and then the following youtube video it seems the using the HLE rsp does not get it quite right either and it should rather be something in the middle for both of my images.

https://youtube.com/watch?v=deBvHxA38hM

I also did not realize mupen64 was still usable, I will have to look into setting that up to see if I can reproduce it there or not. I suspect this is entirely in the mupen64plus core and / or their cxd4 rsp.  Thanks for the reply!

**Comment by cxd4** [comment]
I don't memorize by heart all that I have done to get Mupen64 64-bit working, but it does work out of the box right away with a `make` on my Slack at least:
http://www.emutalk.net/threads/56150-Mupen64-for-x86-64-plugin-developers

It's what I used for the images I uploaded showing my result.  I have historically had the same result also on Windows with Project64 and Hacktarux's untouched 32-bit Mupen64 0.5.

It is a shame that Mupen64Plus broke the plugin system's conformance to other emulators.  If they hadn't, you could take your build of my RSP plugin from Mupen64Plus to some other emulator still using the zilmar-spec plugin model and run it across there.  Seeing the issue gone then would basically prove the CPU core at fault.

I can only think to suggest at the moment winding back to older, legacy versions of Mupen64Plus, possibly back to when they still used the zilmar-spec plugin model (pre-1.5 versions), to see if the older versions of their core (or their fork of my RSP plugin from those years ago) might show when this issue began.

>Furthermore looking at your images and then the following youtube video it seems the using the HLE rsp does not get it quite right either and it should rather be something in the middle for both of my images.

I was aware that the result in your screen captures was off as well, but that isn't caused by the HLE RSP module in Mupen64Plus, which simply asks the graphics plugin to do the RSP emulation for it.  You can probably find better results than what you posted by changing the graphics plugin to one that does HLE more accurately for that game or--in the absence of this issue with my RSP plugin (or ziggy's)--a LLE graphics plugin like angrylion's.

So the `rsp-hle` module is mostly a dummy plugin that gets the video and audio libs to do all the RSP.

**Comment by theboy181** [comment]
Fixed?
