### ISSUE TITLE
Request: yielding in HLE

### ISSUE THREAD

**Issue by olivieryuyu** [cxd4/rsp#8]
I was wondering if there would be a way to get help on the matter explained here:

https://github.com/gonetz/GLideN64/issues/111

Help would be really appreciated!

**Comment by cxd4** [comment]
What seems to be getting discussed there is getting it to work in LLE.

If it's an HLE graphics plugin then it runs the RSP code inside the graphics plugin instead of the RSP plugin, so the RSP code being simulated inside the graphics plugin merely needs simplifying, folding and/or optimizations to remove the extra checks that would happen inside a LLE graphics session from an otherwise working HLE graphics session with _Gauntlet Legends_.

**Comment by olivieryuyu** [comment]
Hello

Not really sure to understand your comments. Sorry for being a bit dummy.

We are not speaking of LLE but indeed HLE.

HLE graphics cannot yield after a CPU request and cannot request a yield to the RSP with current implementation of the RSP/HLE plugins. 

"One issue is this https://github.com/project64/project64/blob/master/Source/RSP/Cpu.c#L216

It always does | 0x203 when using HLE gfx. While in LLE, if it yields, then it does not do | 0x203. So the RSP needs to be modified in order to support yielding in HLE."

**Comment by cxd4** [comment]
Well, that's his opinion.  Yielding thread control is precision for LLE accuracy.  HLE just has the graphics commands pre-translated as if it were a PC port of the game.  It's not meant to function the same way as LLE does, which is where we care about thread-precise control over the RSP, RDP and CPU.

>We are not speaking of LLE but indeed HLE.

True, I recognize that the intended mode of operation is HLE.

The problem however, at least as @LegendOfDragoon is preferring to address it, is LLE graphics.  HLE graphics plugins work with _Gauntlet Legends_ just fine (for example, RiceVideo, Glide64 Final and Jabo's plugin are all HLE and work with that game just fine); there is no need to worry about supporting a yield hack or any such thing because all the RSP code executed is hard-coded inside the HLE graphics plugin with the extra N64-specific cruft simplified out, which needs only be modified to remove the cycle-timing RSP testing from _Gauntlet Legends_' microcode.

Not sure what GlideN64 exactly is doing for HLE.  It sounds like GlideN64 has a dump of the _Gauntlet Legends_ RSP microcode inside the plugin and is executing that?  If so, that's technically HLE but is LLE-precise and can just be optimized down to the essentials of what it would need as a HLE plugin, while still having the game work.

But the way that discussion looks like, it sounds like an LLE solution is being proposed to a HLE plugin.

**Comment by olivieryuyu** [comment]
As far as I am aware, HLE work in Rice, Jabo, etc because there is a hack. The same hack can be implemented in GlideN64, it will work as the rest of the other plugin, **meaning with a lot of graphics issues.** (huge flickering in game)

The hack skips some repeated instructions from the RSP, which is believed to be for yielding (this is a theory) and set things synchronized.

Even LLE needs a tight link between RSP and CPU. See how angrylion plugin works with PJ64 2.3. In game the graphics are getting bad.

I am not expert of course of this matter so if you really think my request is irrelevant, I will close it.

**Comment by cxd4** [comment]
The repeated instructions from the RSP are repeatedd because it's waiting for a yield, like you said.  It's for synchronizing, also like you said.  However, all of this is still from a LLE perspective.

Removing the extra RSP instructions (which don't achieve anything) from HLE that otherwise would execute in LLE isn't really a "hack" any more than HLE itself is.  The purpose of HLE is to translate N64 code into PC code, sort of.  It's a different approach at emulation; that's the reason why Jabo's plugin etc. can play _Gauntlet Legends_ without resorting to a hack.  It's just HLE.

It sounds like it only doesn't work in GlideN64 because it's not really using HLE, or still has LLE cruft left being executed in the HLE'd microcode.

>Even LLE needs a tight link between RSP and CPU. See how angrylion plugin works with PJ64 2.3. In game the graphics are getting bad.

Yeah, the HUD has some black bits in it.  We don't know if it's a CPU interpreter issue with Project64's core instructions or conceivably timing-related.

**Comment by cxd4** [comment]
As far as whether I think your request is relevant or not, I don't know really.

Changing the plugin specs to have task cycle stalling in between manmade HLE microcode segments is just one of many ideas of what could have been done way better about zilmar's plugin specs.  I don't see why it's _needed_ for HLE, but is it useful?  Probably.

The only thing I don't find obvious is why I am being asked about it.  In this RSP plugin I can't control it.

**Comment by Frank-74** [comment]
Would it be better as an emulator extension?  Much like the FBInfo extensions that mupen and 1964 use?

**Comment by cxd4** [comment]
Yeah.  Those were added since the specs were being contributed to "unofficially" (i.e., not by zilmar).

It would be a good extension to the specs but still not something I can do from within this RSP project.

**Comment by LegendOfDragoon** [comment]
basically @olivieryuyu believes that implementing yielding may fix the flickering problem. I got flickering with Jabo LLE, so I'm not quite sure implementing yielding for HLE will fix the problem for GLideN64. Maybe someone can try GlideN64 LLE in gauntlet and see how it is.

However, yielding might be needed for an HLE implementation of WDC, but I never tried to fully HLE it yet.

**Comment by olivieryuyu** [comment]
@cdx4: at least you confirmed that the repeated instructions from the RSP is related to yielding. This is a clue in the right direction as we know that it is not a kind of unimplemented/unknow graphic command (except a fullsync may be). We know why also it does not boot without ignoring the yield calls in the gfx plugin. The devs certainly used a trick here, which is hard on HLE and LLE. 

@LegendOfDragoon: I have the same flickering in game with Jabo LLE, Z64 and Angrylion plugin. I do think that this constant yielding has something to do with it. PJ64 core issue may be also here.

This game is a weird beast anyhow!

**Comment by LegendOfDragoon** [comment]
I initially was against the idea of extending the spec, but it looks like the only decent solution. I looked at the gfx spec and saw that it doesn't have access to RSP registers. You could do something extremely hacky like using a commonly unused RDP register, but I don't see much of a point, other than some quick testing.

I tried skipping the yielding altogether in WDC and can't get it working. Might be something on the cpu side that requires yielding. I always considered just HLEing the RSP code of that game through the RSP, since I wouldn't know how to HLE the RDP anyway.

>@LegendOfDragoon: I have the same flickering in game with Jabo LLE, Z64 and Angrylion plugin. I do think that this constant yielding has something to do with it. PJ64 core issue may be also here.

What part of the game do you see flickering in. I don't recall seeing flickering with Angrylion's. I think Jabo's and Z64 are just unstable for that game. Although I have discovered obscure RSP bugs by testing with Jabo's LLE. I'm thinking the flickering is more of a hardware rendering issue, i'll try testing later on with the z64 software renderer and see if that has any flickering.

>This game is a weird beast anyhow!

Indeed.

**Comment by cxd4** [comment]
The only flickering with angrylion's is if you use the four C buttons to navigate the character's HUD while playing.  If your MP hasn't fully charged to full energy attacks it flickers while animating it, but with angrylion's it just wipes out the HUD instead of flickering the whole screen to black like the other plugins do.

Anyway, an optimized HLE implementation need not concern LLE details like SP_STATUS_REG or its contents on this sort of precision, and can just use the optimized F3DEX C microcode functions that gauntlets calls.  Would not call it an issue with any particular RSP plugin but interesting discussion regardless.

**Comment by olivieryuyu** [comment]
fine, let's close the ticket here.

**Comment by LegendOfDragoon** [comment]
@olivieryuyu if you can tell me where flickering occurs the most, I may try testing out yielding next week and see if that reduces the flickering in HLE.

**Comment by olivieryuyu** [comment]
Well the most is just after the selection screen of your character and before going into the actual game. Here it is horrible how it is flickering.

By the way, no news about your dumping rsp? I would really appreciate your support here! Thx!

**Comment by LegendOfDragoon** [comment]
>Well the most is just after the selection screen of your character and before going into the actual game. Here it is horrible how it is flickering.

Alright, I'll try testing that soon. I forgot to ask, what counter factor are you using?

>By the way, no news about your dumping rsp? I would really appreciate your support here! Thx!

I'll try and finish that soon too.

**Comment by olivieryuyu** [comment]
Yes it does. 

Hmm then may be it is a core issue...

OMG what a game ...!!!!

**Comment by LegendOfDragoon** [comment]
Have you tried Angrylion's latest version? I don't even see the weird VI bug anymore in Gauntlet. I don't see any flickering either. I'll have to see what he changed in his VI code.

I never recalled seeing flickering with Angrylion's in the first place, but I'm glad the VI issue is gone.

**Comment by cxd4** [comment]
son, i am issue.
